## PROJET_01: ***Analyse Exploratoire des Donnees (AED)***
**Realisateur: Thierno Mamoudou BALDE**, *Data Scientist*
* AutoTene est une société de conseil en données fictive. Son client, l'Agence des motos et tricycles de la commune de Gaoual, a fait appel à son équipe pour sa réputation en matière d'accompagnement de ses clients dans le développement de solutions basées sur les données. L'équipe est tout au début du projet. Le Client a mis dispotion l'ensemble des données. Afin d'obtenir des informations pertinentes, les données doivent être analysées, les variables clés identifiées préparées pour l'analyse.

#### Inspection et analyse des données

Examen des données fournies et prépareration pour l’analyse afin de s’assurer que les informations sont :

1. prêtes à répondre aux questions et à fournir des informations pertinentes
2. prêtes pour la visualisation
3. prêtes pour les tests d’hypothèses et les méthodes statistiques ultérieurs

**Objectif:** Explorer et comprehension des données fournies par le client.

**But:**  
* Utiliser un dataframe Python,
* Effectuer une inspection rapide de l’ensemble de données fourni
  
**Objectifs specifiques:**

* Comprendre la situation: *se préparer à comprendre et à organiser l’ensemble de données fourni sur les enggins;*
* Comprendre les données: *créer un dataframe pandas pour l’apprentissage des données, l’analyse exploratoire des données (AED) et les activités statistiques ultérieures;* *Compiler des informations récapitulatives sur les données pour orienter les prochaines étapes*;
* Comprendre les variables: *utiliser les enseignements tirés de l'analyse des données récapitulatives pour approfondir l'étude de variables spécifiques*.

#### **OS1: Comprendre la situation**

* Comment se préparer au mieux pour comprendre et organiser les informations fournies sur les motos et tricycles ?

**Element de réponse :**
Commencer par explorer le jeu de données et consulter le dictionnaire de données. Importer les données dans Python, les examiner minitieusement. L’étape suivante consistera à approfondir l’analyse des données et à rechercher d’éventuelles anomalies.

#### **OS2.a: Création d'un Dataframe python**
Créer un DataFrame pandas pour l'apprentissage des données, ainsi que pour de futures analyses exploratoires (EDA) et activités statistiques.
* Importer les bibliotheques et paquets necessaires pour la création des DataFrames;
  
  **numpy as np**
  
  **pandas as pd**
* Charger le fichier (nom de l'ensemble des données: 2017_Yellow_Taxi_Trip_Data.csv);
* Associez le nom d'objet « df » aux fonctions pandas pour permettre la manipulation facile des données, telles que df.groupby().

In [1]:
import numpy as np
import pandas as pd
# Chargement du fichier
df=pd.read_csv('ag_motos_tricycles.csv')
print('Fichier chargé! Félicitations!')

Fichier chargé! Félicitations!

#### **OS.b. Comprendre les données - Analyser les données**
Afficher et analyser les informations récapitulatives du dataframe en exécutant les commandes suivantes :
1. df.head(10)
2. df.info()
3. df.describe()

**Question 1 :** En examinant le résultat de `df.info()`, que remarquez-vous concernant les différentes variables ? Y a-t-il des valeurs nulles ? Toutes les variables sont-elles numériques ? Y a-t-il d'autres éléments qui attirent votre attention ?

**Question 2 :** En examinant le résultat de `df.describe()`, que remarquez-vous concernant la distribution de chaque variable ? Y a-t-il des valeurs suspectes ?

In [2]:
df.head(5)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

In [3]:
df.describe()

,Unnamed: 0,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,2.269900e+04,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000,22699.000000
mean,5.675849e+07,1.556236,1.642319,2.913313,1.043394,162.412353,161.527997,1.336887,13.026629,0.333275,0.497445,1.835781,0.312542,0.299551,16.310502
std,3.274493e+07,0.496838,1.285231,3.653171,0.708391,66.633373,70.139691,0.496211,13.243791,0.463097,0.039465,2.800626,1.399212,0.015673,16.097295
min,1.212700e+04,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,-120.000000,-1.000000,-0.500000,0.000000,0.000000,-0.300000,-120.300000
25%,2.852056e+07,1.000000,1.000000,0.990000,1.000000,114.000000,112.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.300000,8.750000
50%,5.673150e+07,2.000000,1.000000,1.610000,1.000000,162.000000,162.000000,1.000000,9.500000,0.000000,0.500000,1.350000,0.000000,0.300000,11.800000
75%,8.537452e+07,2.000000,2.000000,3.060000,1.000000,233.000000,233.000000,2.000000,14.500000,0.500000,0.500000,2.450000,0.000000,0.300000,17.800000
max,1.134863e+08,2.000000,6.000000,33.960000,99.000000,265.000000,265.000000,4.000000,999.990000,4.500000,0.500000,200.000000,19.100000,0.300000,1200.290000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22699 entries, 0 to 22698
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             22699 non-null  int64
 1   VendorID               22699 non-null  int64
 2   tpep_pickup_datetime   22699 non-null  object
 3   tpep_dropoff_datetime  22699 non-null  object
 4   passenger_count        22699 non-null  int64
 5   trip_distance          22699 non-null  float64
 6   RatecodeID             22699 non-null  int64
 7   store_and_fwd_flag     22699 non-null  object
 8   PULocationID           22699 non-null  int64
 9   DOLocationID           22699 non-null  int64
 10  payment_type           22699 non-null  int64
 11  fare_amount            22699 non-null  float64
 12  extra                  22699 non-null  float64
 13  mta_tax                22699 non-null  float64
 14  tip_amount             22699 non-null  float64
 15  tolls_amount           22699 non-null  float64
 16  improvement_surcharge  22699 non-null  float64
 17  total_amount           22699 non-null  float64
dtypes: float64(8), int64(7), object(3)
memory usage: 2.9+ MB

**Elements de réponse :**

**Question 1 :** Les types de données sont non numériques. Deux d'entre eux sont de type date/heure.
Aucune valeur  observée.

**Question 2 :** Concernant le montant de la course, la distribution mérite d'être analysée. Le montant maximal (1 000 $) est bien supérieur à la fourchette de valeurs comprises entre 25 % et 75 %. De plus, la présence de valeurs négatives pour le montant de la course est surprenante. Quant à la distance parcourue, la plupart des courses font entre 1 et 3 miles, mais la plus longue dépasse 33 miles.

#### **OS.c: Comprendre les données - Analyser les variables**

Trie et interprétation du tableau de données: deux variables semblent importantes: `trip_distance` et `total_amount`.

**Répondez aux trois questions suivantes :**

**`Question 1 :`** Tri decroissant la première variable (`trip_distance`) .Les valeurs semblent-elles normales ?

**`Question 2 :`** Tri decroissant de la seconde variable (`total_amount`). Quelles observations sur certaines variables?

**`Question 3 :`** Les informations obtenues par les deux tris sont-elles similaires ? Pourquoi ?

In [5]:
# Tri decroissant pour la variable `trip_distance`
df_fltr_trip=df.sort_values(by=['trip_distance'], ascending=False)
# Affichage des donnees triees
df_fltr_trip.head(10)[['trip_distance']]

       trip_distance
9280           33.96
13861          33.92
6064           32.72
10291          31.95
29             30.83
18130          30.50
5792           30.33
15350          28.23
10302          28.20
2592           27.97

In [6]:
# Tri decroissant de l'ensemble de donnees en fonction de 'total_amount'
df_fltr_amount=df.sort_values(by=['total_amount'], ascending=False)
# Affichage des donnees triees
df_fltr_amount.head(10)[['total_amount']]

       total_amount
8476        1200.29
20312        450.30
13861        258.21
12511        233.74
15474        211.80
6064         179.06
16379        157.06
3582         152.30
11269        151.82
9280         150.30

In [7]:
# Afficher les 10 dernieres lignes du tri sur 'total_amount'
df_fltr_amount.tail(10)[['total_amount']]

       total_amount
5448           -4.3
4423           -4.3
10281          -4.3
8204           -4.8
20317          -4.8
11204          -5.3
14714          -5.3
17602          -5.8
20698          -5.8
12944        -120.3

#### NB: ****Les types de paiement sont classifies ainsi qu'il suit:****
* Selon le dictionnaire des donnees, les types de paiement sont codees de la maniere suivante:
  
1 = Credit Card;
2 = Cash; 
3 = No charge; 
4 = Dispute; 
5 = Inconnu; 
6 = Voide trip

In [8]:
# Le nombre de fois chaque type de paiement est représenté dans les données ?
df[['payment_type']].value_counts().reset_index(name='count')

   payment_type  count
0             1  15265
1             2   7267
2             3    121
3             4     46

In [9]:
# Calcul du pourboire moyen (la moyenne des pourboire) pour les voyages payés par carte de crédit ?

fltr_cc = df['payment_type']==1                             # Filtrer par carte de credit
prb_moy = df[fltr_cc]['tip_amount'].mean().round(2)         # Calculer du pourb. moyen pour les voy. par cartes de credits(fltr_cc)

print('Le pourboire moyen pour les voyages par carte de credit est:', prb_moy)

Le pourboire moyen pour les voyages par carte de credit est: 2.73

In [10]:
# Calcul du pourboire moyen (la moyenne des pourboire) pour les voyages payés par cash ?

fltr_cash = df['payment_type']==2                            # Filtrer par carte de credit
prb_moy = df[fltr_cash]['tip_amount'].mean().round(2)         # Calculer du pourb. moyen pour les voy. par cash(fltr_cash)

print('Le pourboire moyen pour les voyages par cash est:', prb_moy)

Le pourboire moyen pour les voyages par cash est: 0.0

In [11]:
# Determiner le nombre de fois chaque vendeur est représenté dans les données
df['VendorID'].value_counts().reset_index(name='count')

   VendorID  count
0         2  12626
1         1  10073

In [12]:
# Calcul de la moyenne du montant total par vendeur
df.groupby('VendorID').mean(numeric_only=True)[['total_amount']].round(2)

          total_amount
VendorID
1                16.30
2                16.32

In [13]:
# Determiner le nombre de passager ayant paye par carte de credit
# D'abord filtrer les donnees pour les voyages payes par credit card
credit_card = df[df['payment_type']==1]
# Ensuite appliquer le mask sur la colonne des passagers
credit_card['passenger_count'].value_counts().reset_index(name='count')

   passenger_count  count
0                1  10977
1                2   2168
2                5    775
3                3    600
4                6    451
5                4    267
6                0     27

In [14]:
# Determiner la moyenne des pourboires pour chaque passager pour les credits card uniquement
credit_card.groupby(['passenger_count']).mean(numeric_only=True)[['tip_amount']].round(2)

                 tip_amount
passenger_count
0                      2.61
1                      2.71
2                      2.83
3                      2.73
4                      2.61
5                      2.76
6                      2.64

**Elements de réponse :**

**Question 1 :** Les valeurs correspondent aux premières observations, révélent que les trajets les plus longs font environ 33 miles.

**Question 2 :** En effet, les deux premières valeurs des tarifs des voyages sont nettement supérieures aux autres.

**Question 3 :** Non ils ne le sont pas. Les trajets les plus chers ne sont forcément pas les plus longs.

**Conclusions :**

Après analyse des données, les deux variables les plus susceptibles de contribuer à l’élaboration d’un modèle prédictif des tarifs de taxi sont: `total_amount` et `trip_distance`, car elles donnent une image fidèle d’une course en motos et tricycles.